---

- name: assert operating system family and version
  block:

    - name: import tasks install
      import_tasks: install.yml
      when: not (openbsd_periodic_state is match('false|no|remove|quiesce|inactive'))

  when: ((ansible_os_family == 'OpenBSD') and (ansible_distribution_version is match('7\.2|7\.3')))
  tags:
    - openbsd_periodic
