---

- name: assert operating system family and version
  block:

    - name: import tasks install
      import_tasks: install.yml
      when: not (bash_state is match('false|no|remove|quiesce|inactive'))

    - name: import tasks remove
      import_tasks: remove.yml
      when: (bash_state is match('false|no|remove'))

  when: ((ansible_os_family == 'OpenBSD') and (ansible_distribution_version is match('7\.2|7\.3')))
  tags:
    - bash
