---

- name: assert operating system family and version
  block:

    - name: import tasks config
      import_tasks: config.yml
      when: not (hosts_state is match('false|no|remove|quiesce|inactive'))

  when: ((ansible_os_family == 'OpenBSD') and (ansible_distribution_version is match('7\.4|7\.5')))
  tags:
    - hosts
